### ISSUE TITLE
Add a few very useful libs

### ISSUE THREAD

**Issue by egordorichev** [pi-pi3/ld-38#1]
Hi! Awesome project. I think, you should add a few more libs to it:

 + https://github.com/rxi/autobatch
 + https://github.com/rxi/lume
 + https://github.com/rxi/lovebpm
 + https://github.com/rxi/log.lua
 + https://github.com/rxi/classic
 + https://github.com/rxi/tick
 + https://github.com/rxi/lurker

And maybe, those small templates:

rect.lua
```lua
local object = require("lib/classic")
local rect = object:extend()

function rect:new(x, y, w, h)
	self.x = x or 0
	self.y = y or 0
	self.w = w or 0
	self.h = h or 0
end

function rect:move(v)
	self.x = self.x + v.x
	self.y = self.y + v.y
end

function rect:intersects(r)
	if rect == nil then
		return false
	end

	return self.x < r.x + r.w and
		r.x < self.x + self.w and
		self.y < r.y + r.h and
		r.y < self.y + self.h
end

function rect:copy()
	return rect(self.x, self.y, self.w, self.h)
end

return rect
```

vector.lua
```lua
local object = require("lib/classic")
local vector = object:extend()

function vector:new(x, y)
    self.x = x or 0
    self.y = y or 0
end

function vector:add(v)
    self.x = self.x + v.x
    self.y = self.y + v.y
end

function vector:subtract(v)
    self.x = self.x - v.x
    self.y = self.y - v.y
end

function vector:multiply(value)
    self.x = self.x * value
    self.y = self.y * value
end

function vector:divide(value)
    self.x = self.x / value
    self.y = self.y / value
end

function vector:set(v)
    self.x = v.x
    self.y = v.y
end

function vector:copy()
    return vector(self.x, self.y)
end

return vector
```

**Comment by pi-pi3** [comment]
Those are great, thanks. I made a new repo just for stuff like that. I'll be adding your mentioned repos as submodules, as well as `rect` and `vec` as soon as I have time (which is right after Ludum Dare).
Check it out [here](https://github.com/pi-pi3/love-template)

**Comment by pi-pi3** [comment]
This is now done. I also added a linked-list implementation. The repository is now located [here](https://github.com/pi-pi3/lib4-lua)

**Comment by pi-pi3** [comment]
This is now done. I also added a singly-linked list implementation. The repository is now located [here](https://github.com/pi-pi3/lib4-lua)
